# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project Olympus Startup Project Teams
email: your-email@domain.com
title: Project Olympus Startup Projects
email: erino@cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a listing of all the current Project Olympus Startup Projects. We do our best to update these company listing, however, for the most up-to-date information regarding the company, you can check their website.
baseurl: "https://olympus-incubator.github.io/startup-project-teams" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: projectolympus
github_username:  olympus-incubator

# Build settings
markdown: kramdown

collections:
    projects:
        output: true
        permalink: /:path
